/*
 * Copyright 2025 Antmicro
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.antmicro.girdl.data.rdl;

public final class RenodeRdl {
	public static final String GUESSED = "Could not determine register's width, guessed 8 bits.";
	public static final String DUMMY = "This is a dummy r/w field, generated just to show the register in specs";
	public static final String ORIGIN = "Generated by RenodeModelsAnalyzer";
}
